#!/sbin/busybox sh

# use this script only if you are tuning existing file
# script check if $2 really exist
# and you need to set or 0 or 1 to tuned file.

if [ "a$2" != "a" ]; then

	filename=$(basename "$2");

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
		if [ -f $2 ]; then
			case "$3" in
				off)
					echo "0" > $2;
				;;
				on)
					echo "1" > $2;
				;;
			esac;
		fi;
	fi;
fi;
