#!/sbin/busybox sh

# use this script only if you are tuning existing file!
# script check if $2 really exist.

if [ "a$2" != "a" ]; then

	filename=$(basename "$2");

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;

		VOL=$3;
		if [ "$3" -lt "0" ]; then
			VOL=$(($3 + 256))
		fi;

		if [ -f $2 ]; then
			echo "$VOL" > $2;
		fi;
	fi;
fi;
