#!/sbin/busybox sh

# $1 - "hotplug_suspend"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	hotplug_suspend=$2;

	case "${hotplug_suspend}" in
		always_active)
			echo "0" > /sys/kernel/alucard_hotplug/hotplug_suspend;
			echo "0" > /sys/module/msm_hotplug/parameters/hotplug_suspend;
			echo "0" > /sys/kernel/intelli_plug/hotplug_suspend;
		;;
		suspend_when_off)
			echo "1" > /sys/kernel/alucard_hotplug/hotplug_suspend;
			echo "1" > /sys/module/msm_hotplug/parameters/hotplug_suspend;
			echo "1" > /sys/kernel/intelli_plug/hotplug_suspend;
		;;
		*)
			hotplug_suspend=always_active;
		;;
	esac;
fi;

echo ${hotplug_suspend};
