#!/sbin/busybox sh

# $1 - "msm_thermal"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	msm_thermal=$2;

	case "${msm_thermal}" in
		msm_temp)
			if [ "$(pgrep -f "/system/bin/thermal-engine" | wc -l)" -eq "0" ]; then
				/system/bin/start thermal-engine;
			fi;
			if [ "$(cat /sys/module/msm_thermal/parameters/intelli_enabled)" == "Y" ]; then
				echo "N" > /sys/module/msm_thermal/parameters/intelli_enabled;
			fi;
			$BB renice -n -17 -p "$(pgrep -f "/system/bin/thermal-engine")";
		;;
		intelli_temp)
			if [ "$(pgrep -f "/system/bin/thermal-engine" | wc -l)" -eq "0" ]; then
				/system/bin/start thermal-engine;
			fi;
			if [ "$(cat /sys/module/msm_thermal/parameters/intelli_enabled)" == "N" ]; then
				echo "Y" > /sys/module/msm_thermal/parameters/intelli_enabled;
				echo "$limit_temp_degC" > /sys/module/msm_thermal/parameters/limit_temp_degC;
				echo "$core_limit_temp_degC" > /sys/module/msm_thermal/parameters/core_limit_temp_degC;
			fi;
			$BB renice -n -17 -p "$(pgrep -f "/system/bin/thermal-engine")";
		;;
		intelli_temp_only)
			if [ "$(cat /sys/module/msm_thermal/parameters/intelli_enabled)" == "N" ]; then
				echo "Y" > /sys/module/msm_thermal/parameters/intelli_enabled;
				echo "$limit_temp_degC" > /sys/module/msm_thermal/parameters/limit_temp_degC;
				echo "$core_limit_temp_degC" > /sys/module/msm_thermal/parameters/core_limit_temp_degC;
			fi;
			if [ "$(pgrep -f "/system/bin/thermal-engine" | wc -l)" -ge "1" ]; then
				/system/bin/stop thermal-engine;
				/system/bin/stop thermal-engine;
				/system/bin/stop thermal-engine;
			fi;
		;;
		*)
			msm_thermal=intelli_temp;
		;;
	esac;
fi;

echo ${msm_thermal};
