#!/sbin/busybox sh

# $1 - "power_mode"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	power_mode=$2;

	GOV0_NAME=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);
	GOV1_NAME=$(cat /sys/devices/system/cpu/cpufreq/all_cpus/scaling_governor_cpu1);
	GOV2_NAME=$(cat /sys/devices/system/cpu/cpufreq/all_cpus/scaling_governor_cpu2);
	GOV3_NAME=$(cat /sys/devices/system/cpu/cpufreq/all_cpus/scaling_governor_cpu3);

	case "${power_mode}" in
		1)
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV0_NAME/sampling_rate ]; then
				echo "10000" > /sys/devices/system/cpu/cpufreq/$GOV0_NAME/sampling_rate;
			fi;
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV1_NAME/sampling_rate ]; then
				echo "10000" > /sys/devices/system/cpu/cpufreq/$GOV1_NAME/sampling_rate;
			fi;
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV2_NAME/sampling_rate ]; then
				echo "10000" > /sys/devices/system/cpu/cpufreq/$GOV2_NAME/sampling_rate;
			fi;
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV3_NAME/sampling_rate ]; then
				echo "10000" > /sys/devices/system/cpu/cpufreq/$GOV3_NAME/sampling_rate;
			fi;
		;;
		0)
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV0_NAME/sampling_rate ]; then
				echo "$sample_rate" > /sys/devices/system/cpu/cpufreq/$GOV0_NAME/sampling_rate;
			fi;
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV1_NAME/sampling_rate ]; then
				echo "$sample_rate" > /sys/devices/system/cpu/cpufreq/$GOV1_NAME/sampling_rate;
			fi;
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV2_NAME/sampling_rate ]; then
				echo "$sample_rate" > /sys/devices/system/cpu/cpufreq/$GOV2_NAME/sampling_rate;
			fi;
			if [ -e /sys/devices/system/cpu/cpufreq/$GOV3_NAME/sampling_rate ]; then
				echo "$sample_rate" > /sys/devices/system/cpu/cpufreq/$GOV3_NAME/sampling_rate;
			fi;
		;;
		*)
			power_mode=0;
		;;
	esac;
fi;

echo ${power_mode};
