#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

BB=/sbin/busybox

if [ "a$2" == "a" ]; then
	echo "$config_backup_restore";
else
	config_backup_restore=$2;
	echo "$config_backup_restore";
fi;

if [ "$(pgrep -f "push-actions/config_backup_restore" | wc -l)" -ge "3" ]; then
	echo "Already working! dont push me!";
	exit 0;
fi;

PROFILE=$(cat /data/.dori/.active.profile);

RELOAD_STWEAKS()
{
	sync;
	am force-stop com.gokhanmoral.stweaks.app 2> /dev/null;
	am start -a android.intent.action.MAIN -n com.gokhanmoral.stweaks.app/.MainActivity 2> /dev/null;
	exit 0;
}

case "${config_backup_restore}" in
	1)
		cp /data/.dori/"$PROFILE".profile /data/.dori/"$PROFILE".profile_backup;
		cp /data/.dori/"$PROFILE".profile /sdcard/"$PROFILE".profile_backup;
		chmod 777 /data/.dori/"$PROFILE".profile_backup;
		echo "Backup of ${PROFILE} profile is Done!";
	;;
	2)
		(
			file2="/data/.dori/${PROFILE}.profile_backup";

			# if someone full wipe the system, then use the profile_backup from sd-card
			if [ ! -e "$file2" ]; then
				file2="/sdcard/${PROFILE}.profile_backup";
			fi;

			if [ ! -e "$file2" ]; then
				echo "You are using ${PROFILE} did you made backup for it??? if you made for other, switch to that profile first!";
				exit;
			fi;

			file1="/data/.dori/${PROFILE}.profile";

			echo "Restoring ${PROFILE} config file, wait for APP RELOAD";

			# read in file1->line1
			while read line1; do
				# split the config into variables where we find "="
				line1_1=$(echo "$line1" | cut -f 1 -d '=');
				line1_2=$(echo "$line1" | cut -f 2 -d '=');

				# grep the content from backup-file ...
				line2=$(grep "^${line1_1}\=" "$file2")
				# ... and also split into variables
				line2_1=$(echo "$line2" | cut -f 1 -d '=');
				line2_2=$(echo "$line2" | cut -f 2 -d '=');

				# compare config- and backup-file
				if [ "a${line1_1}" != "a${line2_1}" ]; then
					# nothing to do -> continue the loop
					continue;
				else
					# if backup-file has different values, then restore it
					if [ "a${line1_2}" != "a${line2_2}" ]; then
						if [ "${line2_2}" != "" ]; then
							$BB sed -i "s/${line1_1}=${line1_2}/${line2_1}=${line2_2}/" "$file1";
							echo "edit: ${line1_1}=${line1_2} -> ${line2_1}=${line2_2}";
						fi;
					else
						# nothing to do -> continue the loop
						# echo "not_edit: ${line1_1}=${line1_2} -> ${line2_1}=${line2_2}";
						continue;
					fi;
				fi;
			done < "$file1"

			# apply New STweaks settings
			$BB sh /res/uci.sh apply > /dev/null;
			RELOAD_STWEAKS;
		)&
	;;
	3)
		(
			$BB cp -a /res/customconfig/battery.profile /data/.dori/;
			echo "battery" > /data/.dori/.active.profile;
			echo "Restoring battery config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			RELOAD_STWEAKS;
		)&
	;;
	4)
		(
			$BB cp -a /res/customconfig/default.profile /data/.dori/;
			echo "default" > /data/.dori/.active.profile;
			echo "Restoring default config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			RELOAD_STWEAKS;
		)&
	;;
	5)
		(
			$BB cp -a /res/customconfig/performance.profile /data/.dori/;
			echo "performance" > /data/.dori/.active.profile;
			echo "Restoring performance config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			RELOAD_STWEAKS;
		)&
	;;
	6)
		(
			$BB cp -a /res/customconfig/extreme_battery.profile /data/.dori/;
			echo "extreme_battery" > /data/.dori/.active.profile;
			echo "Restoring extreme_battery config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			RELOAD_STWEAKS;
		)&
	;;
	7)
		(
			$BB cp -a /res/customconfig/extreme_performance.profile /data/.dori/;
			echo "extreme_performance" > /data/.dori/.active.profile;
			echo "Restoring extreme_performance config file, wait for APP RELOAD";
			$BB sh /res/uci.sh apply > /dev/null;
			RELOAD_STWEAKS;
		)&
	;;
	*)
		echo "need input";
	;;
esac;
