#!/sbin/busybox sh

#created by Dorimanx.

selinux_status=$(grep -c "selinux=0" /proc/cmdline);

if [ "$selinux_status" -eq "0" ]; then
	echo "Kernel Selinux Enabled!";
else
	echo "Kernel Selinux Disabled";
fi;
