#!/sbin/busybox sh

if [ -e /data/data/com.af.synapse ]; then
	echo "Starting Synapse App."
	am start -a android.intent.action.MAIN -n com.af.synapse/.MainActivity > /dev/null;
else
	echo "You don't have Synapse App Installed."
fi;
