#!/sbin/busybox sh

WGET_CHECK1=`ls -la /system/xbin/wget | wc -l`;
WGET_CHECK2=`ls -la /system/bin/wget | wc -l`;

if [ "$WGET_CHECK1" -eq "1" ] || [ "$WGET_CHECK2" -eq "1" ]; then

	TMPFILE=$(mktemp -t);
	mount -o remount,rw /;

	DNS1=`getprop net.dns1`;
	DNS2=`getprop net.rmnet0.dns1`;
	DNS3=`getprop net.rmnet0.dns2`;

	echo "nameserver 8.8.8.8" > /system/etc/resolv.conf;
	echo "nameserver 4.4.8.8" >> /system/etc/resolv.conf;
	echo "nameserver $DNS1" >> /system/etc/resolv.conf;
	echo "nameserver $DNS2" >> /system/etc/resolv.conf;
	echo "nameserver $DNS3" >> /system/etc/resolv.conf;

	TESTCONNECTION=`wget http://www.google.com -O $TMPFILE > /dev/null 2>&1`;
	if [ $? != 0 ]; then
		echo "Problem: no internet connection! connect and try again";
	else
		(
			ntpd -n -q -p `cat /system/etc/gps.conf | grep NTP_SERVER | cut -f 2 -d "="`;
		)&
		echo "updated time via ntp";
	fi;

	rm -f $TMPFILE;
else
	echo "Your BusyBox is not supported! Update to latest";
fi;
