#!/sbin/busybox sh

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

if [ "$crontab" == "on" ]; then
	if [ "$(pgrep -f crond | wc -l)" -eq "0" ]; then
		$BB nohup $BB sh /res/crontab_service/service.sh > /dev/null 2>&1;
	fi;
fi;

CRON_SERVICE=$(pgrep -f "crond" | wc -l);
if [ "$CRON_SERVICE" != 0 ]; then
	echo "Service is ONLINE and supported";
else
	echo "Service is OFFLINE or NOT supported";
fi;
