#!/sbin/busybox sh

if [ ! -e /data/crontab/cron-clear-file-cache ]; then
	echo "no data" > /data/crontab/cron-clear-file-cache;
fi;
if [ ! -e /data/crontab/cron-clear-ram-cache ]; then
	echo "no data" > /data/crontab/cron-clear-ram-cache;
fi;
if [ ! -e /data/crontab/cron-zipalign ]; then
	echo "no data" > /data/crontab/cron-zipalign;
fi;
if [ ! -e /data/crontab/cron-ad_block_update ]; then
	echo "no data" > /data/crontab/cron-ad_block_update;
fi;
if [ ! -e /data/crontab/cron-db-optimizing ]; then
	echo "no data" > /data/crontab/cron-db-optimizing;
fi;
chmod 777 /data/crontab/*
cat /data/crontab/cron-clear-file-cache > /data/crontab/cron_log;
echo "---" >> /data/crontab/cron_log;
cat /data/crontab/cron-ad_block_update >> /data/crontab/cron_log;
echo "---" >> /data/crontab/cron_log;
cat /data/crontab/cron-clear-ram-cache >> /data/crontab/cron_log;
echo "---" >> /data/crontab/cron_log;
cat /data/crontab/cron-db-optimizing >> /data/crontab/cron_log;
echo "---" >> /data/crontab/cron_log;
cat /data/crontab/cron-zipalign >> /data/crontab/cron_log;

# push all to one log.
CRON_LOG=$(cat /data/crontab/cron_log);
echo "$CRON_LOG";
