#!/sbin/busybox sh

WGET_CHECK1=`ls /system/wget/wget | wc -l` > /dev/null 2>&1;

if [ "$WGET_CHECK1" -eq "1" ]; then

	mount -o remount,rw /;
	mount -o remount,rw /system;

	DNS1=`getprop net.dns1`;
	DNS2=`getprop net.rmnet0.dns1`;
	DNS3=`getprop net.rmnet0.dns2`;

	echo "nameserver 8.8.8.8" > /system/etc/resolv.conf;
	echo "nameserver 4.4.8.8" >> /system/etc/resolv.conf;
	echo "nameserver $DNS1" >> /system/etc/resolv.conf;
	echo "nameserver $DNS2" >> /system/etc/resolv.conf;
	echo "nameserver $DNS3" >> /system/etc/resolv.conf;

	TMPFILE=$(mktemp -t);
	TMPFILE2=$(mktemp -t);
	OLD_VERSION=`cat /proc/version | sed 's/.*-V//g' | sed 's/-I.*//g' | sed 's/-/ /g' | awk '{print $1}'`;

	TESTCONNECTION=`wget http://www.google.com -O $TMPFILE > /dev/null 2>&1`;
	if [ $? != 0 ]; then
		echo "Problem: no internet connection! connect and try again";
	else
		wget http://www.dorimanx.com/LG/ -O $TMPFILE > /dev/null 2>&1;
		cat $TMPFILE | grep ".*-V" |  sed 's/.*-V//g' | sed 's/S.*//g' | sed 's/-I.*//g' | sed 's/[-\[].*//g' | sort -r > $TMPFILE2;

		for version in $(cat $TMPFILE2); do
			expr "$OLD_VERSION" \< "$version" >/dev/null && echo "There is a new version of this kernel available!!!" && break;
			expr "$OLD_VERSION" \= "$version" >/dev/null && echo "You already using the most advanced kernel in the world!" && break;
			expr "$OLD_VERSION" \> "$version" >/dev/null && echo "Kernel that you have is not my lattest version! check mirror for correct version" && break;
		done;
	fi;

	rm $TMPFILE;
	rm $TMPFILE2;

	mount -o remount,ro /system;
else
	echo "Your System dont have WGET binary from my kernel, reinstall my kernel.";
fi;
