#!/sbin/busybox sh

# $1 - "adb_selector"
# $2 - value=
# Created By Dorimanx

if [ ! -e /data/.dori/adbd_selector ]; then
	echo "adbd_lg" > /data/.dori/adbd_selector;
fi;

ADB_SELECTOR=$(cat /data/.dori/adbd_selector);

if [ "a$2" != "a" ]; then
	adb_selector=$2;

	case "${adb_selector}" in
	1)
		if [ "$ADB_SELECTOR" == "adbd_su" ]; then
			stop adbd
			echo 0 > /sys/class/android_usb/android0/enable
			rm -f /sbin/adbd;
			ln -s /sbin/adbd_lg /sbin/adbd;
			echo 1 > /sys/class/android_usb/android0/enable
			start adbd
			echo "adbd_lg" > /data/.dori/adbd_selector;
		else
			echo "adbd_lg" > /data/.dori/adbd_selector;
		fi;
	;;
	0)
		stop adbd
		echo 0 > /sys/class/android_usb/android0/enable
		rm -f /sbin/adbd;
		ln -s /sbin/adbd_su /sbin/adbd;
		echo 1 > /sys/class/android_usb/android0/enable
		start adbd
		echo "adbd_su" > /data/.dori/adbd_selector;
	;;
	*)
		adb_selector=1;
	;;
	esac;
fi;
echo ${adb_selector};
