#!/sbin/busybox sh

# $1 - "cpu0_max_freq"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

if [ "$cortexbrain_cpu" == "on" ]; then
	if [ "a$2" != "a" ]; then
		cpu0_max_freq=$2;

		echo "0" > /sys/kernel/msm_cpufreq_limit/cpufreq_limit_cpu0;
		echo "$cpu0_max_freq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
		echo "$cpu0_max_freq" > /sys/kernel/msm_cpufreq_limit/cpufreq_limit_cpu0;
	fi;
fi;

echo ${cpu0_max_freq};
