#!/sbin/busybox sh

# $1 - "cpu1_max_freq"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

if [ "$cortexbrain_cpu" == "on" ]; then
	if [ "a$2" != "a" ]; then
		cpu1_max_freq=$2;

		echo "0" > /sys/kernel/msm_cpufreq_limit/cpufreq_limit_cpu1;
		echo "$cpu1_max_freq" > /sys/devices/system/cpu/cpufreq/all_cpus/scaling_max_freq_cpu1;
		echo "$cpu1_max_freq" > /sys/kernel/msm_cpufreq_limit/cpufreq_limit_cpu1;
	fi;
fi;

echo ${cpu1_max_freq};
