#!/sbin/busybox sh

# $1 - "crontab_switch"
# $2 - value=
# Created By Dorimanx and Dairinin

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	crontab_switch=$2;

	case "${crontab_switch}" in
		on)
			(
				if [ "$(pidof crond | wc -l)" -eq "0" ]; then
					$BB sh /res/crontab_service/service.sh > /dev/null;
				fi;
			)&
		;;
		off)
			pkill -f crond;
		;;
		*)
			crontab_switch=on;
		;;
	esac;
fi;

echo ${crontab_switch};
