#!/sbin/busybox sh

# $1 - "hotplug_sample_rate"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	hotplug_sample_rate=$2;

	echo "$hotplug_sample_rate" > /sys/kernel/alucard_hotplug/hotplug_sampling_rate;
	echo "$hotplug_sample_rate" > /sys/kernel/intelli_plug/def_sampling_ms;
	echo "$hotplug_sample_rate" > /sys/module/msm_hotplug/update_rates;
fi;

echo ${hotplug_sample_rate};
