#!/sbin/busybox sh

# $1 - "oom_config_screen_on"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $oom_config_screen_on;
else
	oom_config_screen_on=$2;
	echo "$oom_config_screen_on";
fi;

PROFILE=`cat /data/.dori/.active.profile`;
AUTO_OOM=`cat /data/.dori/${PROFILE}.profile | grep auto_oom=on | wc -l`

if [ "$AUTO_OOM" -eq "1" ]; then
	case "${oom_config_screen_on}" in
		medium)
			echo "18432,23040,24576,28672,31744,34816" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "48" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		default)
			echo "18432,23040,27648,32356,46080,51200" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		stock)
			echo "18432,23040,27648,32356,49152,61440" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		aggressive)
			echo "18432,23040,27648,34816,51200,65536" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		exterminate)
			echo "18432,23040,27648,53760,58880,65536" > /sys/module/lowmemorykiller/parameters/minfree;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		*)
			oom_config_screen_on=default;
		;;
	esac;
fi;
