#!/sbin/busybox sh

# $1 - "oom_config_screen_off"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $oom_config_screen_off;
else
	oom_config_screen_off=$2;
	echo "$oom_config_screen_off";
fi;

PROFILE=`cat /data/.dori/.active.profile`;
AUTO_OOM=`cat /data/.dori/${PROFILE}.profile | grep auto_oom=on | wc -l`

if [ "$AUTO_OOM" -eq "1" ]; then
	case "${oom_config_screen_off}" in
		low)
			echo "4096,8192,16384,24576,28672,32768" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "48" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		medium)
			echo "4096,8192,16384,28672,31744,34816" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "48" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		default)
			echo "4096,8192,16384,28672,46080,51200" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "32" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		aggressive)
			echo "4096,8192,16384,34816,51200,65536" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		exterminate)
			echo "4096,8192,16384,53760,58880,65536" > /sys/module/lowmemorykiller/parameters/minfree_screen_off;
			echo "16" > /sys/module/lowmemorykiller/parameters/cost;
		;;
		*)
			oom_config_screen_off=default;
		;;
	esac;
fi;
