#!/sbin/busybox sh

# $1 - "suspend_min_freq"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	suspend_min_freq=$2;

	if [ "$suspend_min_freq" == "min_freq" ]; then
		echo "0" > /sys/kernel/msm_cpufreq_limit/suspend_min_freq;
	else
		echo "$suspend_min_freq" > /sys/kernel/msm_cpufreq_limit/suspend_min_freq;
	fi;
fi;

echo ${suspend_min_freq};
