#!/sbin/busybox sh

# $1 - "suspend_min_freq"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	suspend_min_freq=$2;

	echo "$suspend_min_freq" > /sys/kernel/msm_cpufreq_limit/suspend_min_freq;
fi;

echo ${suspend_min_freq};
